# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Jekyll Actions
        # You may pin to the exact commit or the version.
        uses: helaili/jekyll-action@2.2.0
        with:
          # The GITHUB_TOKEN secret
          token: ${{ secrets.GITHUB_TOKEN }}
          # The Jekyll environment to build
          jekyll_env: production bundle exec jekyll build --destination site # optional

          # Do not overwrite whatever was already published on the target branch
          keep_history: true # optional
          # Commands to run prior to build and deploy. Useful for ensuring build dependencies are up to date or installing  new dependencies. For example, use `apk --update add  imagemagick` to install ImageMagick.

          pre_build_commands: |
            wget -O ./_data/voorwoord.yml https://raw.githubusercontent.com/jensdufour/ScoutsNinove/master/_data/voorwoord.yml
            wget -O ./_data/programma.yml https://raw.githubusercontent.com/jensdufour/ScoutsNinove/master/_data/programma.yml
