name: Build & FTP Upload Site
# Run on pushes to the master branch
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
      with:
        fetch-depth: 2
    - uses: ruby/setup-ruby@v1.89.0
      with:
        ruby-version: '3.0.3'

    # Install the gems in the gemfile & install ncftp
    - name: Setup Environment
      run: |
        bundle install

    # Get the needed files      
    - name: Get files
      run: |
        wget -O ./_data/voorwoord.yml https://raw.githubusercontent.com/jensdufour/ScoutsNinove/master/_data/voorwoord.yml
        wget -O ./_data/programma.yml https://raw.githubusercontent.com/jensdufour/ScoutsNinove/master/_data/programma.yml

    # Build the site
    - name: Build Site with Jekyll.
      run: JEKYLL_ENV=production bundle exec jekyll build

    # Publish to Pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
        publish_dir: ./site
        github_token: ${{ secrets.GITHUB_TOKEN }}

